- name: check golang mine path exist
  tags: 
    - golang
    - virtualbox
  command: test -d {{ my_gopath }}
  register: my_gopath_check
  failed_when : my_gopath_check.rc not in [0,1]

- name: remove golang mine path
  tags: 
    - golang
    - virtualbox
  when: my_gopath_check.rc == 0
  file: >
    path={{ my_gopath }}
    state=absent

- name: check golang shared path exist
  tags: 
    - golang
    - virtualbox
  command: test -d {{ gopath_shared_path }}
  register: gopath_shared_check
  failed_when : gopath_shared_check.rc not in [0,1]

- name: create golang shared path
  tags: 
    - golang
    - virtualbox
  when: gopath_shared_check.rc != 0
  file: >
    path={{ gopath_shared_path }}
    state=directory

- name: craete symbolik link by shared folder for Gopath
  tags: 
    - golang
    - virtualbox
  file: >
    src={{ gopath_shared_path }}
    path={{ my_gopath }}
    state=link
