- name: NeoBundle directory check
  tags:
    - vim
  command: test -d {{ neobundle_path }}
  register: neobundle_dir_check
  failed_when: neobundle_dir_check.rc not in [0,1]

- name: NeoBundle download
  tags:
    - vim
  when: neobundle_dir_check.rc != 0
  git: >
    repo=https://github.com/Shougo/neobundle.vim
    dest={{ neobundle_path }}

- name: exec NeoBundleInstall
  tags:
    - vim
  command: "{{ neobundle_path }}/bin/neoinstall"
